# Spring系列框架的设置
spring:
  datasource:
    # 连接数据库的URL
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 登录数据库的用户名
    username: root
    # 登录数据库的密码
    password: root
